services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=projects_db'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=admin'
    volumes:
      - projects_db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - projects_db-net
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8088:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: sara@gmail.com
      PGADMIN_DEFAULT_PASSWORD: azer
    volumes:
      - projects_db_pgadmin_data:/var/lib/pgadmin
    networks:
      - projects_db-net
volumes:
  projects_db_data:
  projects_db_pgadmin_data:

networks:
  projects_db-net:
    driver: bridge